#!/bin/bash

#
# Automatic Updater/Installer for the
#    Automated Android Build Script
#
# Author:	Lukas Berger <mail@lukasberger.at>
# Date:		03-05-2017
#

# download and extract
git clone https://github.com/TeamNexus/aabs/
cd ./aabs/

# prepare and launch
chmod +x ./bin/aabs
./bin/aabs -f "./aabs-projects"
