#!/usr/bin/php
<?php

define('AABS_BASEDIR', dirname($argv[0]));
define('AABS_START_TIME', time());

// include global constants
include AABS_BASEDIR . "/core/const.php";

// include utilities
include AABS_BASEDIR . "/core/utils.php";

// include remote-plugins
include AABS_BASEDIR . "/remote/ftp.php";
include AABS_BASEDIR . "/remote/sftp.php";
include AABS_BASEDIR . "/remote/mega.php";
	
// include core-functions
include AABS_BASEDIR . "/core/sync.php";
include AABS_BASEDIR . "/core/build.php";
include AABS_BASEDIR . "/core/patch.php";
include AABS_BASEDIR . "/core/upload.php";

// parse arguments, load configurations and start building
include AABS_BASEDIR . "/core/core.php";
