#!/bin/bash

#
# Automatic Updater/Installer for the
#    Automated Android Build Script
#
# Author:	Lukas Berger <mail@lukasberger.at>
# Date:		03-05-2017
#

AABS_URL="https://github.com/TeamNexus/aabs/archive/master.zip"

# download and extract
curl -L ${AABS_URL} > aabs.zip
rm -rf aabs/
unzip aabs.zip
mv aabs-master/ aabs/

# prepare and launch
chmod +x aabs/src/aabs
./aabs/src/aabs
