#!/bin/bash

#
# Automated Android Build Script - Simple and automated Android Build-Script
# Copyright (C) 2017  Lukas Berger
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# set global indicator variable
AABS=1
AABS_BASEDIR=$(dirname $0)

# include libs
. $AABS_BASEDIR/lib/variables.sh
. $AABS_BASEDIR/lib/list.sh
. $AABS_BASEDIR/lib/build.sh

# startup
function aabs_main {
	file=$1

	if [ ! -f $file ]; then
		exit 1
	fi

	# parse the project list
	aabs_parse_list $file project_list

	for project in "${project_list[@]}"; do

		project=( $project )

		aabs_parse_variable ${project[0]} ${project[1]}
		ret=$?

		if [ $ret -eq 1 ]; then
			# no build-action, so continue
			continue
		fi

		# [0] codename
		# [1] model
		# [2] rom-name
		# [3] rom-source
		# [4] lunch-combo
		# [5] output-expr
		# [6] upload-path
		# [7] clobber
		# [8] concr-jobs

		# prepare build-variables
		aabs_get_value "codename"    ${project[0]}
		aabs_get_value "model"       ${project[1]}
		aabs_get_value "rom-name"    ${project[2]}
		aabs_get_value "rom-source"  ${project[3]}
		aabs_get_value "lunch-combo" ${project[4]}
		aabs_get_value "output-expr" ${project[5]}
		aabs_get_value "upload-path" ${project[6]}
		aabs_get_value "clobber"     ${project[7]}
		aabs_get_value "concr-jobs"  ${project[8]}

		export __date=$(date +%Y-%m-%d)
		export __time=$(date +%H%M)

		# expand variables: lunch-combo
		aabs_expand_variable "lunch-combo" "codename"
		aabs_expand_variable "lunch-combo" "model"
		aabs_expand_variable "lunch-combo" "rom-name"

		# expand variables: upload-path
		aabs_expand_variable "upload-path" "codename"
		aabs_expand_variable "upload-path" "model"
		aabs_expand_variable "upload-path" "rom-name"
		aabs_expand_variable "upload-path" "date"
		aabs_expand_variable "upload-path" "time"

		# expand variables: rom-source
		aabs_expand_variable "rom-source" "codename"
		aabs_expand_variable "rom-source" "model"
		aabs_expand_variable "rom-source" "rom-name"

		# start build
		start_build

	done

}

# default project file
aabs_main ./aabs-projects

for file in "$@"
do
	# passed project files
   aabs_main $file
done
